services:
  api:
    image: phoenix-nodeuser
    container_name: phoenix-api
    ports:
      - "8080:5000"
    environment:
      - DATABASE_URI=mongodb://database:27017/phoenix
    depends_on:
      - database
    networks:
      - phoenix-net

  database:
    image: mongo:latest
    container_name: phoenix-db
    volumes:
      - mongo-data:/data/db
    networks:
      - phoenix-net

volumes:
  mongo-data:

networks:
  phoenix-net: